### ISSUE TITLE
关于票档选择

### ISSUE THREAD

**Issue by deavose** [surqing/-Autox.js-#1]
您好，我拿您的鹿晗js文件进行复制，导入到了手机，我想问下选择票档这里的文字是将他们改成我要买的内个票的票档吗，我将“预售单日票 ：480元”改成“1380元（站票）”然后就会卡在选择票档没有反应，我想问下这个是怎么回事呢

**Comment by surqing** [comment]
你好，如果你测试的门票已经可以购买，则不应该卡在终端输出为"选择票档"的位置，如果你测试的门票还没有开售，那么卡在选择票档的位置是正常的，后面的点击是否可以正常执行你需要用一个当前可以下单的门票进行测试

**Comment by deavose** [comment]
![2562a238f3111d419b117acf9428e25](https://github.com/surqing/-Autox.js-/assets/115394913/c2b483d1-702e-4876-8374-00e9f331eac1)
![8601bcded2306728835e080cefe8d96](https://github.com/surqing/-Autox.js-/assets/115394913/6e389203-5c46-4354-aa71-551bb6db23b8)
您好，我是用的就是当前可以下单的门票，您看我这个修改是否有问题？或者是分辨率问题？我目前分辨率为2400*1080

**Comment by surqing** [comment]
建议你取消每一步下面在终端输出的print语句的注释，这样可以方便知道脚本当前执行到了哪一步。还要注意场次和票档中的文字和符号必须与界面中的文字一致。我更新了最新的脚本，尝试一下在最新的上面进行修改

**Comment by deavose** [comment]
您好，我使用了您的最新脚本，它会卡在点了立即购买之后，不会进行场次选择，场次时间我就修改日期，将7-14改为了7-15，周五修改为周六，应该是没什么问题才对，不太清楚为什么会这样
![45dd2ab79134a146600534851b0d1fa](https://github.com/surqing/-Autox.js-/assets/115394913/d6bf2bce-6729-4dae-945a-3b56f8c4d3ca)
![7d8a5ee4344a5e548ddd8a121fbb122](https://github.com/surqing/-Autox.js-/assets/115394913/5c6c3229-0a08-4e03-8a1e-b4c9af6f727b)

**Comment by surqing** [comment]
尝试修改代码85行的.parent()数目进行测试

**Comment by deavose** [comment]
没有用，修改之后没有区别

**Comment by surqing** [comment]
可以参考官方文档使用autoxjs的布局范围分析功能，对组件点击进行生成代码，你的问题可能存在于
1，字符与组件的字符不一致，建议打开autox.js菜单中的悬浮窗功能，点击出现的悬浮窗中蓝色的按钮，对需要点击的组件进行布局范围分析，参考官方文档
2，通过字符识别找到组件不可被点击，可点击的组件是其父组件，可用while循环判断组件的clickable()属性，找到是该组件的第一个父组件是可以被点击的，代码如下：
// 找到可点击的组件
var bt = text("2023-07-14 周五 19:30").findOne();
var i = 0;
while (!bt.checkable()) {
    i = i + 1;
    bt = bt.parent();
}
print(i); // i 就是 text("2023-07-14 周五 19:30").findOne() 组件的第几个父组件是可以被点击的

如果组件点击无法实现可以尝试坐标点击，参考官方文档

**Comment by wahahababaozhou** [comment]
大麦改了场次跟票档的组件，无法再通过text获取到组件了，有什么好的解决方式吗？

**Comment by surqing** [comment]
click函数可以直接选择屏幕的坐标，你可以参考官方文档在 2024年5月23日，16:32，哇哈哈八宝粥 ***@***.***> 写道：﻿
大麦改了场次跟票档的组件，无法再通过text获取到组件了，有什么好的解决方式吗？

**Comment by wahahababaozhou** [comment]
大麦APP那个立即抢购按钮，现在通过click坐标的方式也点不了了，不知道是怎么限制的https://github.com/kkevsekk1/AutoX/issues/892#issue-2254424190

**Comment by surqing** [comment]
那我也不知道了哈在 2024年5月29日，17:15，哇哈哈八宝粥 ***@***.***> 写道：﻿
大麦APP那个立即抢购按钮，现在通过click坐标的方式也点不了了，不知道是怎么限制的kkevsekk1/AutoX#892 (comment)
