### ISSUE TITLE
关于优化建议

### ISSUE THREAD

**Issue by Chang-L12138** [surqing/-Autox.js-#2]
你好，可以编写一个用bp抢的js吗

**Comment by surqing** [comment]
不好意思，目前没有时间再写新的脚本，如果你会一点点编程基础的话建议你自己尝试写一下，这种脚本调用的接口非常少，无非就是找到组件然后点击，如遇到不懂的可以询问 chatgpt 或者查阅官方文档

如果你不会编程建议你简单学习一下 python，这对你的学习和工作都会有一点帮助的。我没学过 js，但是会 python ，你会发现他们都是类似的

**Comment by Chang-L12138** [comment]
我可不可以请教一下，加入我想从app中直接打开 https://m.damai.cn/damai/detail/sku.html?id=727698795527 这种页面需要怎么操作呢？

**Comment by surqing** [comment]
根据autoxjs的官方文档中的描述，此功能需要获取root权限，http://doc.autoxjs.com/#/app?id=appstartactivityname
