### ISSUE TITLE
薛之谦成都

### ISSUE THREAD

**Issue by 1071382355** [surqing/-Autox.js-#4]
兄弟，可以弄一个薛之谦成都的吗，或者加个联系方式，呜呜呜太需要你了

**Comment by surqing** [comment]
经过几轮的测试，这个脚本在实际抢票过程中还是很难抢到票。提交订单的时候会出现当前购买人数较多的错误，大麦可能对脚本抢票做了防范，如果要测试达到这个脚本实际可用应该还需要做很多的处理和测试，但是我目前还有学业任务，没有多余的时间研究。**其次，很重要的一点是，放在大麦平台上的票可能大部分都被黄牛拿走了（不知道用的什么方法），能给普通用户抢的票数量非常少**，如果你只是想去看演唱会但没抢到票的话，其实邻近开演唱会的时候闲鱼上**可能**有比原价还要低的票
