### ISSUE TITLE
怎么用啊

### ISSUE THREAD

**Issue by YY-KK-YY** [surqing/-Autox.js-#7]
新手不会用，有大佬会吗

**Comment by surqing** [comment]
https://github.com/kkevsekk1/AutoX/releases/tag/6.4.3
在上面的链接下载 universal 版本的 autoxjs ，安装在手机上，打开应用按照指示让应用获取相应的权限，在应用的右上角点击➕号，选择文件，命名随意，注意要勾选 js 文件，然后将本项目的 js脚本复制粘贴在刚刚的文件中，修改你要抢的票的场次和票档所对应的参数，打开大麦，进入到你想抢票的页面，返回 autoxjs，点击运行，到达时间后脚本会自动点击，如果你不确定脚本会不会正常执行，你可以尝试使用 v1.3 版本测试已经能够购买的票，看看能否自动点击
